
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch main
# Your branch is up to date with 'origin/main'.
#
# Changes to be committed:
#	new file:   __init__.py
#	new file:   __pycache__/__init__.cpython-37.pyc
#	new file:   _dashboard/__init__.py
#	new file:   _dashboard/__pycache__/__init__.cpython-37.pyc
#	new file:   _dashboard/__pycache__/diff2kryten.cpython-37.pyc
#	new file:   _dashboard/__pycache__/utils.cpython-37.pyc
#	new file:   _dashboard/diff2kryten.py
#	new file:   _dashboard/static/components/mtable.html
#	new file:   _dashboard/static/components/mtable.js
#	new file:   _dashboard/static/css/future.css
#	new file:   _dashboard/static/css/gitlog.min.css
#	new file:   _dashboard/static/favicon.ico
#	new file:   _dashboard/static/images/alert-blue.gif
#	new file:   _dashboard/static/images/alert-green.gif
#	new file:   _dashboard/static/images/alert-orange.gif
#	new file:   _dashboard/static/images/alert-red.gif
#	new file:   _dashboard/static/images/alert-yellow.gif
#	new file:   _dashboard/static/images/forkme.png
#	new file:   _dashboard/static/images/widget.gif
#	new file:   _dashboard/static/js/ace/ace.js
#	new file:   _dashboard/static/js/ace/ext-beautify.js
#	new file:   _dashboard/static/js/ace/ext-chromevox.js
#	new file:   _dashboard/static/js/ace/ext-elastic_tabstops_lite.js
#	new file:   _dashboard/static/js/ace/ext-emmet.js
#	new file:   _dashboard/static/js/ace/ext-error_marker.js
#	new file:   _dashboard/static/js/ace/ext-keybinding_menu.js
#	new file:   _dashboard/static/js/ace/ext-language_tools.js
#	new file:   _dashboard/static/js/ace/ext-linking.js
#	new file:   _dashboard/static/js/ace/ext-modelist.js
#	new file:   _dashboard/static/js/ace/ext-old_ie.js
#	new file:   _dashboard/static/js/ace/ext-searchbox.js
#	new file:   _dashboard/static/js/ace/ext-settings_menu.js
#	new file:   _dashboard/static/js/ace/ext-spellcheck.js
#	new file:   _dashboard/static/js/ace/ext-split.js
#	new file:   _dashboard/static/js/ace/ext-static_highlight.js
#	new file:   _dashboard/static/js/ace/ext-statusbar.js
#	new file:   _dashboard/static/js/ace/ext-textarea.js
#	new file:   _dashboard/static/js/ace/ext-themelist.js
#	new file:   _dashboard/static/js/ace/ext-whitespace.js
#	new file:   _dashboard/static/js/ace/keybinding-emacs.js
#	new file:   _dashboard/static/js/ace/keybinding-vim.js
#	new file:   _dashboard/static/js/ace/mode-abap.js
#	new file:   _dashboard/static/js/ace/mode-abc.js
#	new file:   _dashboard/static/js/ace/mode-actionscript.js
#	new file:   _dashboard/static/js/ace/mode-ada.js
#	new file:   _dashboard/static/js/ace/mode-apache_conf.js
#	new file:   _dashboard/static/js/ace/mode-applescript.js
#	new file:   _dashboard/static/js/ace/mode-asciidoc.js
#	new file:   _dashboard/static/js/ace/mode-assembly_x86.js
#	new file:   _dashboard/static/js/ace/mode-autohotkey.js
#	new file:   _dashboard/static/js/ace/mode-batchfile.js
#	new file:   _dashboard/static/js/ace/mode-bro.js
#	new file:   _dashboard/static/js/ace/mode-c9search.js
#	new file:   _dashboard/static/js/ace/mode-c_cpp.js
#	new file:   _dashboard/static/js/ace/mode-cirru.js
#	new file:   _dashboard/static/js/ace/mode-clojure.js
#	new file:   _dashboard/static/js/ace/mode-cobol.js
#	new file:   _dashboard/static/js/ace/mode-coffee.js
#	new file:   _dashboard/static/js/ace/mode-coldfusion.js
#	new file:   _dashboard/static/js/ace/mode-csharp.js
#	new file:   _dashboard/static/js/ace/mode-css.js
#	new file:   _dashboard/static/js/ace/mode-curly.js
#	new file:   _dashboard/static/js/ace/mode-d.js
#	new file:   _dashboard/static/js/ace/mode-dart.js
#	new file:   _dashboard/static/js/ace/mode-diff.js
#	new file:   _dashboard/static/js/ace/mode-django.js
#	new file:   _dashboard/static/js/ace/mode-dockerfile.js
#	new file:   _dashboard/static/js/ace/mode-dot.js
#	new file:   _dashboard/static/js/ace/mode-drools.js
#	new file:   _dashboard/static/js/ace/mode-eiffel.js
#	new file:   _dashboard/static/js/ace/mode-ejs.js
#	new file:   _dashboard/static/js/ace/mode-elixir.js
#	new file:   _dashboard/static/js/ace/mode-elm.js
#	new file:   _dashboard/static/js/ace/mode-erlang.js
#	new file:   _dashboard/static/js/ace/mode-forth.js
#	new file:   _dashboard/static/js/ace/mode-fortran.js
#	new file:   _dashboard/static/js/ace/mode-ftl.js
#	new file:   _dashboard/static/js/ace/mode-gcode.js
#	new file:   _dashboard/static/js/ace/mode-gherkin.js
#	new file:   _dashboard/static/js/ace/mode-gitignore.js
#	new file:   _dashboard/static/js/ace/mode-glsl.js
#	new file:   _dashboard/static/js/ace/mode-gobstones.js
#	new file:   _dashboard/static/js/ace/mode-golang.js
#	new file:   _dashboard/static/js/ace/mode-groovy.js
#	new file:   _dashboard/static/js/ace/mode-haml.js
#	new file:   _dashboard/static/js/ace/mode-handlebars.js
#	new file:   _dashboard/static/js/ace/mode-haskell.js
#	new file:   _dashboard/static/js/ace/mode-haskell_cabal.js
#	new file:   _dashboard/static/js/ace/mode-haxe.js
#	new file:   _dashboard/static/js/ace/mode-hjson.js
#	new file:   _dashboard/static/js/ace/mode-html.js
#	new file:   _dashboard/static/js/ace/mode-html_elixir.js
#	new file:   _dashboard/static/js/ace/mode-html_ruby.js
#	new file:   _dashboard/static/js/ace/mode-ini.js
#	new file:   _dashboard/static/js/ace/mode-io.js
#	new file:   _dashboard/static/js/ace/mode-jack.js
#	new file:   _dashboard/static/js/ace/mode-jade.js
#	new file:   _dashboard/static/js/ace/mode-java.js
#	new file:   _dashboard/static/js/ace/mode-javascript.js
#	new file:   _dashboard/static/js/ace/mode-json.js
#	new file:   _dashboard/static/js/ace/mode-jsoniq.js
#	new file:   _dashboard/static/js/ace/mode-jsp.js
#	new file:   _dashboard/static/js/ace/mode-jsx.js
#	new file:   _dashboard/static/js/ace/mode-julia.js
#	new file:   _dashboard/static/js/ace/mode-kotlin.js
#	new file:   _dashboard/static/js/ace/mode-latex.js
#	new file:   _dashboard/static/js/ace/mode-lean.js
#	new file:   _dashboard/static/js/ace/mode-less.js
#	new file:   _dashboard/static/js/ace/mode-liquid.js
#	new file:   _dashboard/static/js/ace/mode-lisp.js
#	new file:   _dashboard/static/js/ace/mode-live_script.js
#	new file:   _dashboard/static/js/ace/mode-livescript.js
#	new file:   _dashboard/static/js/ace/mode-logiql.js
#	new file:   _dashboard/static/js/ace/mode-lsl.js
#	new file:   _dashboard/static/js/ace/mode-lua.js
#	new file:   _dashboard/static/js/ace/mode-luapage.js
#	new file:   _dashboard/static/js/ace/mode-lucene.js
#	new file:   _dashboard/static/js/ace/mode-makefile.js
#	new file:   _dashboard/static/js/ace/mode-markdown.js
#	new file:   _dashboard/static/js/ace/mode-mask.js
#	new file:   _dashboard/static/js/ace/mode-matlab.js
#	new file:   _dashboard/static/js/ace/mode-maze.js
#	new file:   _dashboard/static/js/ace/mode-mel.js
#	new file:   _dashboard/static/js/ace/mode-mips_assembler.js
#	new file:   _dashboard/static/js/ace/mode-mipsassembler.js
#	new file:   _dashboard/static/js/ace/mode-mushcode.js
#	new file:   _dashboard/static/js/ace/mode-mysql.js
#	new file:   _dashboard/static/js/ace/mode-nix.js
#	new file:   _dashboard/static/js/ace/mode-nsis.js
#	new file:   _dashboard/static/js/ace/mode-objectivec.js
#	new file:   _dashboard/static/js/ace/mode-ocaml.js
#	new file:   _dashboard/static/js/ace/mode-pascal.js
#	new file:   _dashboard/static/js/ace/mode-perl.js
#	new file:   _dashboard/static/js/ace/mode-pgsql.js
#	new file:   _dashboard/static/js/ace/mode-php.js
#	new file:   _dashboard/static/js/ace/mode-plain_text.js
#	new file:   _dashboard/static/js/ace/mode-powershell.js
#	new file:   _dashboard/static/js/ace/mode-praat.js
#	new file:   _dashboard/static/js/ace/mode-prolog.js
#	new file:   _dashboard/static/js/ace/mode-properties.js
#	new file:   _dashboard/static/js/ace/mode-protobuf.js
#	new file:   _dashboard/static/js/ace/mode-python.js
#	new file:   _dashboard/static/js/ace/mode-r.js
#	new file:   _dashboard/static/js/ace/mode-razor.js
#	new file:   _dashboard/static/js/ace/mode-rdoc.js
#	new file:   _dashboard/static/js/ace/mode-rhtml.js
#	new file:   _dashboard/static/js/ace/mode-rst.js
#	new file:   _dashboard/static/js/ace/mode-ruby.js
#	new file:   _dashboard/static/js/ace/mode-rust.js
#	new file:   _dashboard/static/js/ace/mode-sass.js
#	new file:   _dashboard/static/js/ace/mode-scad.js
#	new file:   _dashboard/static/js/ace/mode-scala.js
#	new file:   _dashboard/static/js/ace/mode-scheme.js
#	new file:   _dashboard/static/js/ace/mode-scss.js
#	new file:   _dashboard/static/js/ace/mode-sh.js
#	new file:   _dashboard/static/js/ace/mode-sjs.js
#	new file:   _dashboard/static/js/ace/mode-smarty.js
#	new file:   _dashboard/static/js/ace/mode-snippets.js
#	new file:   _dashboard/static/js/ace/mode-soy_template.js
#	new file:   _dashboard/static/js/ace/mode-space.js
#	new file:   _dashboard/static/js/ace/mode-sql.js
#	new file:   _dashboard/static/js/ace/mode-sqlserver.js
#	new file:   _dashboard/static/js/ace/mode-stylus.js
#	new file:   _dashboard/static/js/ace/mode-svg.js
#	new file:   _dashboard/static/js/ace/mode-swift.js
#	new file:   _dashboard/static/js/ace/mode-swig.js
#	new file:   _dashboard/static/js/ace/mode-tcl.js
#	new file:   _dashboard/static/js/ace/mode-tex.js
#	new file:   _dashboard/static/js/ace/mode-text.js
#	new file:   _dashboard/static/js/ace/mode-textile.js
#	new file:   _dashboard/static/js/ace/mode-toml.js
#	new file:   _dashboard/static/js/ace/mode-tsx.js
#	new file:   _dashboard/static/js/ace/mode-twig.js
#	new file:   _dashboard/static/js/ace/mode-typescript.js
#	new file:   _dashboard/static/js/ace/mode-vala.js
#	new file:   _dashboard/static/js/ace/mode-vbscript.js
#	new file:   _dashboard/static/js/ace/mode-velocity.js
#	new file:   _dashboard/static/js/ace/mode-verilog.js
#	new file:   _dashboard/static/js/ace/mode-vhdl.js
#	new file:   _dashboard/static/js/ace/mode-wollok.js
#	new file:   _dashboard/static/js/ace/mode-xml.js
#	new file:   _dashboard/static/js/ace/mode-xquery.js
#	new file:   _dashboard/static/js/ace/mode-yaml.js
#	new file:   _dashboard/static/js/ace/snippets/abap.js
#	new file:   _dashboard/static/js/ace/snippets/abc.js
#	new file:   _dashboard/static/js/ace/snippets/actionscript.js
#	new file:   _dashboard/static/js/ace/snippets/ada.js
#	new file:   _dashboard/static/js/ace/snippets/apache_conf.js
#	new file:   _dashboard/static/js/ace/snippets/applescript.js
#	new file:   _dashboard/static/js/ace/snippets/asciidoc.js
#	new file:   _dashboard/static/js/ace/snippets/assembly_x86.js
#	new file:   _dashboard/static/js/ace/snippets/autohotkey.js
#	new file:   _dashboard/static/js/ace/snippets/batchfile.js
#	new file:   _dashboard/static/js/ace/snippets/bro.js
#	new file:   _dashboard/static/js/ace/snippets/c9search.js
#	new file:   _dashboard/static/js/ace/snippets/c_cpp.js
#	new file:   _dashboard/static/js/ace/snippets/cirru.js
#	new file:   _dashboard/static/js/ace/snippets/clojure.js
#	new file:   _dashboard/static/js/ace/snippets/cobol.js
#	new file:   _dashboard/static/js/ace/snippets/coffee.js
#	new file:   _dashboard/static/js/ace/snippets/coldfusion.js
#	new file:   _dashboard/static/js/ace/snippets/csharp.js
#	new file:   _dashboard/static/js/ace/snippets/css.js
#	new file:   _dashboard/static/js/ace/snippets/curly.js
#	new file:   _dashboard/static/js/ace/snippets/d.js
#	new file:   _dashboard/static/js/ace/snippets/dart.js
#	new file:   _dashboard/static/js/ace/snippets/diff.js
#	new file:   _dashboard/static/js/ace/snippets/django.js
#	new file:   _dashboard/static/js/ace/snippets/dockerfile.js
#	new file:   _dashboard/static/js/ace/snippets/dot.js
#	new file:   _dashboard/static/js/ace/snippets/drools.js
#	new file:   _dashboard/static/js/ace/snippets/eiffel.js
#	new file:   _dashboard/static/js/ace/snippets/ejs.js
#	new file:   _dashboard/static/js/ace/snippets/elixir.js
#	new file:   _dashboard/static/js/ace/snippets/elm.js
#	new file:   _dashboard/static/js/ace/snippets/erlang.js
#	new file:   _dashboard/static/js/ace/snippets/forth.js
#	new file:   _dashboard/static/js/ace/snippets/fortran.js
#	new file:   _dashboard/static/js/ace/snippets/ftl.js
#	new file:   _dashboard/static/js/ace/snippets/gcode.js
#	new file:   _dashboard/static/js/ace/snippets/gherkin.js
#	new file:   _dashboard/static/js/ace/snippets/gitignore.js
#	new file:   _dashboard/static/js/ace/snippets/glsl.js
#	new file:   _dashboard/static/js/ace/snippets/gobstones.js
#	new file:   _dashboard/static/js/ace/snippets/golang.js
#	new file:   _dashboard/static/js/ace/snippets/groovy.js
#	new file:   _dashboard/static/js/ace/snippets/haml.js
#	new file:   _dashboard/static/js/ace/snippets/handlebars.js
#	new file:   _dashboard/static/js/ace/snippets/haskell.js
#	new file:   _dashboard/static/js/ace/snippets/haskell_cabal.js
#	new file:   _dashboard/static/js/ace/snippets/haxe.js
#	new file:   _dashboard/static/js/ace/snippets/hjson.js
#	new file:   _dashboard/static/js/ace/snippets/html.js
#	new file:   _dashboard/static/js/ace/snippets/html_elixir.js
#	new file:   _dashboard/static/js/ace/snippets/html_ruby.js
#	new file:   _dashboard/static/js/ace/snippets/ini.js
#	new file:   _dashboard/static/js/ace/snippets/io.js
#	new file:   _dashboard/static/js/ace/snippets/jack.js
#	new file:   _dashboard/static/js/ace/snippets/jade.js
#	new file:   _dashboard/static/js/ace/snippets/java.js
#	new file:   _dashboard/static/js/ace/snippets/javascript.js
#	new file:   _dashboard/static/js/ace/snippets/json.js
#	new file:   _dashboard/static/js/ace/snippets/jsoniq.js
#	new file:   _dashboard/static/js/ace/snippets/jsp.js
#	new file:   _dashboard/static/js/ace/snippets/jsx.js
#	new file:   _dashboard/static/js/ace/snippets/julia.js
#	new file:   _dashboard/static/js/ace/snippets/kotlin.js
#	new file:   _dashboard/static/js/ace/snippets/latex.js
#	new file:   _dashboard/static/js/ace/snippets/lean.js
#	new file:   _dashboard/static/js/ace/snippets/less.js
#	new file:   _dashboard/static/js/ace/snippets/liquid.js
#	new file:   _dashboard/static/js/ace/snippets/lisp.js
#	new file:   _dashboard/static/js/ace/snippets/live_script.js
#	new file:   _dashboard/static/js/ace/snippets/livescript.js
#	new file:   _dashboard/static/js/ace/snippets/logiql.js
#	new file:   _dashboard/static/js/ace/snippets/lsl.js
#	new file:   _dashboard/static/js/ace/snippets/lua.js
#	new file:   _dashboard/static/js/ace/snippets/luapage.js
#	new file:   _dashboard/static/js/ace/snippets/lucene.js
#	new file:   _dashboard/static/js/ace/snippets/makefile.js
#	new file:   _dashboard/static/js/ace/snippets/markdown.js
#	new file:   _dashboard/static/js/ace/snippets/mask.js
#	new file:   _dashboard/static/js/ace/snippets/matlab.js
#	new file:   _dashboard/static/js/ace/snippets/maze.js
#	new file:   _dashboard/static/js/ace/snippets/mel.js
#	new file:   _dashboard/static/js/ace/snippets/mips_assembler.js
#	new file:   _dashboard/static/js/ace/snippets/mipsassembler.js
#	new file:   _dashboard/static/js/ace/snippets/mushcode.js
#	new file:   _dashboard/static/js/ace/snippets/mysql.js
#	new file:   _dashboard/static/js/ace/snippets/nix.js
#	new file:   _dashboard/static/js/ace/snippets/nsis.js
#	new file:   _dashboard/static/js/ace/snippets/objectivec.js
#	new file:   _dashboard/static/js/ace/snippets/ocaml.js
#	new file:   _dashboard/static/js/ace/snippets/pascal.js
#	new file:   _dashboard/static/js/ace/snippets/perl.js
#	new file:   _dashboard/static/js/ace/snippets/pgsql.js
#	new file:   _dashboard/static/js/ace/snippets/php.js
#	new file:   _dashboard/static/js/ace/snippets/plain_text.js
#	new file:   _dashboard/static/js/ace/snippets/powershell.js
#	new file:   _dashboard/static/js/ace/snippets/praat.js
#	new file:   _dashboard/static/js/ace/snippets/prolog.js
#	new file:   _dashboard/static/js/ace/snippets/properties.js
#	new file:   _dashboard/static/js/ace/snippets/protobuf.js
#	new file:   _dashboard/static/js/ace/snippets/python.js
#	new file:   _dashboard/static/js/ace/snippets/r.js
#	new file:   _dashboard/static/js/ace/snippets/razor.js
#	new file:   _dashboard/static/js/ace/snippets/rdoc.js
#	new file:   _dashboard/static/js/ace/snippets/rhtml.js
#	new file:   _dashboard/static/js/ace/snippets/rst.js
#	new file:   _dashboard/static/js/ace/snippets/ruby.js
#	new file:   _dashboard/static/js/ace/snippets/rust.js
#	new file:   _dashboard/static/js/ace/snippets/sass.js
#	new file:   _dashboard/static/js/ace/snippets/scad.js
#	new file:   _dashboard/static/js/ace/snippets/scala.js
#	new file:   _dashboard/static/js/ace/snippets/scheme.js
#	new file:   _dashboard/static/js/ace/snippets/scss.js
#	new file:   _dashboard/static/js/ace/snippets/sh.js
#	new file:   _dashboard/static/js/ace/snippets/sjs.js
#	new file:   _dashboard/static/js/ace/snippets/smarty.js
#	new file:   _dashboard/static/js/ace/snippets/snippets.js
#	new file:   _dashboard/static/js/ace/snippets/soy_template.js
#	new file:   _dashboard/static/js/ace/snippets/space.js
#	new file:   _dashboard/static/js/ace/snippets/sql.js
#	new file:   _dashboard/static/js/ace/snippets/sqlserver.js
#	new file:   _dashboard/static/js/ace/snippets/stylus.js
#	new file:   _dashboard/static/js/ace/snippets/svg.js
#	new file:   _dashboard/static/js/ace/snippets/swift.js
#	new file:   _dashboard/static/js/ace/snippets/swig.js
#	new file:   _dashboard/static/js/ace/snippets/tcl.js
#	new file:   _dashboard/static/js/ace/snippets/tex.js
#	new file:   _dashboard/static/js/ace/snippets/text.js
#	new file:   _dashboard/static/js/ace/snippets/textile.js
#	new file:   _dashboard/static/js/ace/snippets/toml.js
#	new file:   _dashboard/static/js/ace/snippets/tsx.js
#	new file:   _dashboard/static/js/ace/snippets/twig.js
#	new file:   _dashboard/static/js/ace/snippets/typescript.js
#	new file:   _dashboard/static/js/ace/snippets/vala.js
#	new file:   _dashboard/static/js/ace/snippets/vbscript.js
#	new file:   _dashboard/static/js/ace/snippets/velocity.js
#	new file:   _dashboard/static/js/ace/snippets/verilog.js
#	new file:   _dashboard/static/js/ace/snippets/vhdl.js
#	new file:   _dashboard/static/js/ace/snippets/wollok.js
#	new file:   _dashboard/static/js/ace/snippets/xml.js
#	new file:   _dashboard/static/js/ace/snippets/xquery.js
#	new file:   _dashboard/static/js/ace/snippets/yaml.js
#	new file:   _dashboard/static/js/ace/theme-ambiance.js
#	new file:   _dashboard/static/js/ace/theme-chaos.js
#	new file:   _dashboard/static/js/ace/theme-chrome.js
#	new file:   _dashboard/static/js/ace/theme-clouds.js
#	new file:   _dashboard/static/js/ace/theme-clouds_midnight.js
#	new file:   _dashboard/static/js/ace/theme-cobalt.js
#	new file:   _dashboard/static/js/ace/theme-crimson_editor.js
#	new file:   _dashboard/static/js/ace/theme-dawn.js
#	new file:   _dashboard/static/js/ace/theme-dreamweaver.js
#	new file:   _dashboard/static/js/ace/theme-eclipse.js
#	new file:   _dashboard/static/js/ace/theme-github.js
#	new file:   _dashboard/static/js/ace/theme-idle_fingers.js
#	new file:   _dashboard/static/js/ace/theme-iplastic.js
#	new file:   _dashboard/static/js/ace/theme-katzenmilch.js
#	new file:   _dashboard/static/js/ace/theme-kr_theme.js
#	new file:   _dashboard/static/js/ace/theme-kuroir.js
#	new file:   _dashboard/static/js/ace/theme-merbivore.js
#	new file:   _dashboard/static/js/ace/theme-merbivore_soft.js
#	new file:   _dashboard/static/js/ace/theme-mono_industrial.js
#	new file:   _dashboard/static/js/ace/theme-monokai.js
#	new file:   _dashboard/static/js/ace/theme-pastel_on_dark.js
#	new file:   _dashboard/static/js/ace/theme-solarized_dark.js
#	new file:   _dashboard/static/js/ace/theme-solarized_light.js
#	new file:   _dashboard/static/js/ace/theme-sqlserver.js
#	new file:   _dashboard/static/js/ace/theme-terminal.js
#	new file:   _dashboard/static/js/ace/theme-textmate.js
#	new file:   _dashboard/static/js/ace/theme-tomorrow.js
#	new file:   _dashboard/static/js/ace/theme-tomorrow_night.js
#	new file:   _dashboard/static/js/ace/theme-tomorrow_night_blue.js
#	new file:   _dashboard/static/js/ace/theme-tomorrow_night_bright.js
#	new file:   _dashboard/static/js/ace/theme-tomorrow_night_eighties.js
#	new file:   _dashboard/static/js/ace/theme-twilight.js
#	new file:   _dashboard/static/js/ace/theme-vibrant_ink.js
#	new file:   _dashboard/static/js/ace/theme-xcode.js
#	new file:   _dashboard/static/js/ace/worker-coffee.js
#	new file:   _dashboard/static/js/ace/worker-css.js
#	new file:   _dashboard/static/js/ace/worker-html.js
#	new file:   _dashboard/static/js/ace/worker-javascript.js
#	new file:   _dashboard/static/js/ace/worker-json.js
#	new file:   _dashboard/static/js/ace/worker-lua.js
#	new file:   _dashboard/static/js/ace/worker-php.js
#	new file:   _dashboard/static/js/ace/worker-xml.js
#	new file:   _dashboard/static/js/ace/worker-xquery.js
#	new file:   _dashboard/static/js/axios.min.js
#	new file:   _dashboard/static/js/dbadmin.js
#	new file:   _dashboard/static/js/highlight.min.js
#	new file:   _dashboard/static/js/index.js
#	new file:   _dashboard/static/js/jquery.min.js
#	new file:   _dashboard/static/js/sugar.min.js
#	new file:   _dashboard/static/js/utils.js
#	new file:   _dashboard/static/js/vue.min.js
#	new file:   _dashboard/templates/dbadmin.html
#	new file:   _dashboard/templates/gitlog.html
#	new file:   _dashboard/templates/index.html
#	new file:   _dashboard/templates/ticket.html
#	new file:   _dashboard/translations/README.md
#	new file:   _dashboard/utils.py
#	new file:   _default/__init__.py
#	new file:   _default/__pycache__/__init__.cpython-37.pyc
#	new file:   _default/static/favicon.ico
#	new file:   _default/templates/index.html
#	new file:   _documentation/__init__.py
#	new file:   _documentation/__pycache__/__init__.cpython-37.pyc
#	new file:   _documentation/static/en/.buildinfo
#	new file:   _documentation/static/en/.doctrees/chapter-01.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-02.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-03.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-04.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-05.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-06.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-07.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-08.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-09.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-10.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-11.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-12.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-13.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-14.doctree
#	new file:   _documentation/static/en/.doctrees/chapter-15.doctree
#	new file:   _documentation/static/en/.doctrees/environment.pickle
#	new file:   _documentation/static/en/.doctrees/index.doctree
#	new file:   _documentation/static/en/.nojekyll
#	new file:   _documentation/static/en/_images/command.png
#	new file:   _documentation/static/en/_images/dashboard.png
#	new file:   _documentation/static/en/_images/dashboard_edit.png
#	new file:   _documentation/static/en/_images/dashboard_error.png
#	new file:   _documentation/static/en/_images/dashboard_login.png
#	new file:   _documentation/static/en/_images/dashboard_main.png
#	new file:   _documentation/static/en/_images/dashboard_restapi.png
#	new file:   _documentation/static/en/_images/dashboard_ticket.png
#	new file:   _documentation/static/en/_images/first_run.png
#	new file:   _documentation/static/en/_images/main_page.png
#	new file:   _documentation/static/en/_sources/chapter-01.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-02.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-03.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-04.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-05.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-06.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-07.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-08.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-09.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-10.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-11.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-12.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-13.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-14.rst.txt
#	new file:   _documentation/static/en/_sources/chapter-15.rst.txt
#	new file:   _documentation/static/en/_sources/index.rst.txt
#	new file:   _documentation/static/en/_static/basic.css
#	new file:   _documentation/static/en/_static/css/badge_only.css
#	new file:   _documentation/static/en/_static/css/dark.css
#	new file:   _documentation/static/en/_static/css/fonts/Roboto-Slab-Bold.woff
#	new file:   _documentation/static/en/_static/css/fonts/Roboto-Slab-Bold.woff2
#	new file:   _documentation/static/en/_static/css/fonts/Roboto-Slab-Regular.woff
#	new file:   _documentation/static/en/_static/css/fonts/Roboto-Slab-Regular.woff2
#	new file:   _documentation/static/en/_static/css/fonts/fontawesome-webfont.eot
#	new file:   _documentation/static/en/_static/css/fonts/fontawesome-webfont.svg
#	new file:   _documentation/static/en/_static/css/fonts/fontawesome-webfont.ttf
#	new file:   _documentation/static/en/_static/css/fonts/fontawesome-webfont.woff
#	new file:   _documentation/static/en/_static/css/fonts/fontawesome-webfont.woff2
#	new file:   _documentation/static/en/_static/css/fonts/lato-bold-italic.woff
#	new file:   _documentation/static/en/_static/css/fonts/lato-bold-italic.woff2
#	new file:   _documentation/static/en/_static/css/fonts/lato-bold.woff
#	new file:   _documentation/static/en/_static/css/fonts/lato-bold.woff2
#	new file:   _documentation/static/en/_static/css/fonts/lato-normal-italic.woff
#	new file:   _documentation/static/en/_static/css/fonts/lato-normal-italic.woff2
#	new file:   _documentation/static/en/_static/css/fonts/lato-normal.woff
#	new file:   _documentation/static/en/_static/css/fonts/lato-normal.woff2
#	new file:   _documentation/static/en/_static/css/theme.css
#	new file:   _documentation/static/en/_static/css/toggle.css
#	new file:   _documentation/static/en/_static/doctools.js
#	new file:   _documentation/static/en/_static/documentation_options.js
#	new file:   _documentation/static/en/_static/file.png
#	new file:   _documentation/static/en/_static/jquery-3.5.1.js
#	new file:   _documentation/static/en/_static/jquery.js
#	new file:   _documentation/static/en/_static/js/badge_only.js
#	new file:   _documentation/static/en/_static/js/html5shiv-printshiv.min.js
#	new file:   _documentation/static/en/_static/js/html5shiv.min.js
#	new file:   _documentation/static/en/_static/js/theme.js
#	new file:   _documentation/static/en/_static/js/toggle.js
#	new file:   _documentation/static/en/_static/language_data.js
#	new file:   _documentation/static/en/_static/minus.png
#	new file:   _documentation/static/en/_static/plus.png
#	new file:   _documentation/static/en/_static/pygments.css
#	new file:   _documentation/static/en/_static/searchtools.js
#	new file:   _documentation/static/en/_static/underscore.js
#	new file:   _documentation/static/en/chapter-01.html
#	new file:   _documentation/static/en/chapter-02.html
#	new file:   _documentation/static/en/chapter-03.html
#	new file:   _documentation/static/en/chapter-04.html
#	new file:   _documentation/static/en/chapter-05.html
#	new file:   _documentation/static/en/chapter-06.html
#	new file:   _documentation/static/en/chapter-07.html
#	new file:   _documentation/static/en/chapter-08.html
#	new file:   _documentation/static/en/chapter-09.html
#	new file:   _documentation/static/en/chapter-10.html
#	new file:   _documentation/static/en/chapter-11.html
#	new file:   _documentation/static/en/chapter-12.html
#	new file:   _documentation/static/en/chapter-13.html
#	new file:   _documentation/static/en/chapter-14.html
#	new file:   _documentation/static/en/chapter-15.html
#	new file:   _documentation/static/en/dark.css
#	new file:   _documentation/static/en/genindex.html
#	new file:   _documentation/static/en/index.html
#	new file:   _documentation/static/en/objects.inv
#	new file:   _documentation/static/en/search.html
#	new file:   _documentation/static/en/searchindex.js
#	new file:   _documentation/static/en/toggle.css
#	new file:   _documentation/static/favicon.ico
#	new file:   _documentation/static/index.html
#	new file:   _minimal/__init__.py
#	new file:   _minimal/__pycache__/__init__.cpython-37.pyc
#	new file:   _minimal/static/README.md
#	new file:   _minimal/static/favicon.ico
#	new file:   _scaffold/__init__.py
#	new file:   _scaffold/__pycache__/__init__.cpython-37.pyc
#	new file:   _scaffold/__pycache__/common.cpython-37.pyc
#	new file:   _scaffold/__pycache__/controllers.cpython-37.pyc
#	new file:   _scaffold/__pycache__/models.cpython-37.pyc
#	new file:   _scaffold/__pycache__/settings.cpython-37.pyc
#	new file:   _scaffold/common.py
#	new file:   _scaffold/controllers.py
#	new file:   _scaffold/databases/README.md
#	new file:   _scaffold/databases/fb87181b96a99be45f5a23f4277867ce_auth_user.table
#	new file:   _scaffold/databases/fb87181b96a99be45f5a23f4277867ce_auth_user_tag_groups.table
#	new file:   _scaffold/databases/sql.log
#	new file:   _scaffold/databases/storage.db
#	new file:   _scaffold/models.py
#	new file:   _scaffold/settings.py
#	new file:   _scaffold/static/README.md
#	new file:   _scaffold/static/css/no.css
#	new file:   _scaffold/static/favicon.ico
#	new file:   _scaffold/static/js/utils.js
#	new file:   _scaffold/tasks.py
#	new file:   _scaffold/templates/README.md
#	new file:   _scaffold/templates/auth.html
#	new file:   _scaffold/templates/generic.html
#	new file:   _scaffold/templates/index.html
#	new file:   _scaffold/templates/layout.html
#	new file:   _scaffold/translations/it.json
#	new file:   _websocket/__init__.py
#	new file:   _websocket/__pycache__/__init__.cpython-37.pyc
#	new file:   _websocket/static/README.md
#	new file:   _websocket/static/favicon.ico
#	new file:   _websocket/templates/index.html
#	new file:   examples/__init__.py
#	new file:   examples/__pycache__/__init__.cpython-37.pyc
#	new file:   examples/__pycache__/common.cpython-37.pyc
#	new file:   examples/__pycache__/controllers.cpython-37.pyc
#	new file:   examples/__pycache__/controllers_components.cpython-37.pyc
#	new file:   examples/__pycache__/models.cpython-37.pyc
#	new file:   examples/__pycache__/settings.cpython-37.pyc
#	new file:   examples/common.py
#	new file:   examples/components/README.md
#	new file:   examples/components/__pycache__/fileupload.cpython-37.pyc
#	new file:   examples/components/__pycache__/grid.cpython-37.pyc
#	new file:   examples/components/__pycache__/starrater.cpython-37.pyc
#	new file:   examples/components/__pycache__/vueform.cpython-37.pyc
#	new file:   examples/components/fileupload.py
#	new file:   examples/components/grid.py
#	new file:   examples/components/starrater.py
#	new file:   examples/components/vueform.py
#	new file:   examples/controllers.py
#	new file:   examples/controllers_components.py
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_auth_user.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_auth_user_tag_groups.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_person.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_product.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_superhero.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_superpower.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_tag.table
#	new file:   examples/databases/fb87181b96a99be45f5a23f4277867ce_thing.table
#	new file:   examples/databases/sql.log
#	new file:   examples/databases/storage.db
#	new file:   examples/models.py
#	new file:   examples/settings.py
#	new file:   examples/socketio/__init__.py
#	new file:   examples/static/components-bulma/fileupload/fileupload.css
#	new file:   examples/static/components-bulma/fileupload/fileupload.html
#	new file:   examples/static/components-bulma/fileupload/fileupload.js
#	new file:   examples/static/components-bulma/grid/grid.css
#	new file:   examples/static/components-bulma/grid/grid.html
#	new file:   examples/static/components-bulma/grid/grid.js
#	new file:   examples/static/components-bulma/mtable.html
#	new file:   examples/static/components-bulma/mtable.js
#	new file:   examples/static/components-bulma/starrater/starrater.css
#	new file:   examples/static/components-bulma/starrater/starrater.html
#	new file:   examples/static/components-bulma/starrater/starrater.js
#	new file:   examples/static/components-bulma/vueform/luxon.js
#	new file:   examples/static/components-bulma/vueform/luxon.min.js
#	new file:   examples/static/components-bulma/vueform/vueform.css
#	new file:   examples/static/components-bulma/vueform/vueform.html
#	new file:   examples/static/components-bulma/vueform/vueform.js
#	new file:   examples/static/components/fileupload/fileupload.css
#	new file:   examples/static/components/fileupload/fileupload.html
#	new file:   examples/static/components/fileupload/fileupload.js
#	new file:   examples/static/components/grid/grid.css
#	new file:   examples/static/components/grid/grid.html
#	new file:   examples/static/components/grid/grid.js
#	new file:   examples/static/components/mtable.html
#	new file:   examples/static/components/mtable.js
#	new file:   examples/static/components/starrater/starrater.css
#	new file:   examples/static/components/starrater/starrater.html
#	new file:   examples/static/components/starrater/starrater.js
#	new file:   examples/static/components/vueform/luxon.js
#	new file:   examples/static/components/vueform/luxon.min.js
#	new file:   examples/static/components/vueform/vueform.css
#	new file:   examples/static/components/vueform/vueform.html
#	new file:   examples/static/components/vueform/vueform.js
#	new file:   examples/static/css/no.css
#	new file:   examples/static/favicon.ico
#	new file:   examples/static/firebase-push.html
#	new file:   examples/static/hello.txt
#	new file:   examples/static/js/axios.min.js
#	new file:   examples/static/js/axios.min.map
#	new file:   examples/static/js/firebase-push.js
#	new file:   examples/static/js/star_rater_vue.js
#	new file:   examples/static/js/sugar.min.js
#	new file:   examples/static/js/utils.js
#	new file:   examples/static/js/vue.js
#	new file:   examples/static/js/vue.min.js
#	new file:   examples/static/socketio/README.md
#	new file:   examples/static/ws/README.md
#	new file:   examples/templates/ajax_grid.html
#	new file:   examples/templates/auth_custom_login.html
#	new file:   examples/templates/auth_form.html
#	new file:   examples/templates/auth_forms.html
#	new file:   examples/templates/component_loader.html
#	new file:   examples/templates/custom_form.html
#	new file:   examples/templates/file_uploader.html
#	new file:   examples/templates/flash_example.html
#	new file:   examples/templates/flash_example_next.html
#	new file:   examples/templates/form.html
#	new file:   examples/templates/forms.html
#	new file:   examples/templates/generic.html
#	new file:   examples/templates/html_grid.html
#	new file:   examples/templates/index.html
#	new file:   examples/templates/layout.html
#	new file:   examples/templates/layout_bulma.html
#	new file:   examples/templates/page_with_template.html
#	new file:   examples/templates/session_counter.html
#	new file:   examples/templates/socketio/index.html
#	new file:   examples/templates/star_rater_vue.html
#	new file:   examples/templates/star_rater_vue_bulma.html
#	new file:   examples/templates/starrating.html
#	new file:   examples/templates/tagsinput_form.html
#	new file:   examples/templates/vueform.html
#	new file:   examples/templates/vueform_bulma.html
#	new file:   examples/templates/vuegrid.html
#	new file:   examples/templates/vuegrid_bulma.html
#	new file:   examples/templates/ws/index.html
#	new file:   examples/translations/en.json
#	new file:   examples/translations/it.json
#	new file:   examples/ws/__init__.py
#	new file:   examples/ws/test-websocket.py
#	new file:   hso_project/__pycache__/__init__.cpython-37.pyc
#	new file:   hso_project/__pycache__/common.cpython-37.pyc
#	new file:   hso_project/__pycache__/controllers.cpython-37.pyc
#	new file:   hso_project/__pycache__/models.cpython-37.pyc
#	new file:   hso_project/__pycache__/settings.cpython-37.pyc
#	new file:   myfeed/README.md
#	new file:   myfeed/__init__.py
#	new file:   myfeed/__pycache__/__init__.cpython-37.pyc
#	new file:   myfeed/__pycache__/common.cpython-37.pyc
#	new file:   myfeed/__pycache__/controllers.cpython-37.pyc
#	new file:   myfeed/__pycache__/make_up_data.cpython-37.pyc
#	new file:   myfeed/__pycache__/models.cpython-37.pyc
#	new file:   myfeed/__pycache__/settings.cpython-37.pyc
#	new file:   myfeed/common.py
#	new file:   myfeed/controllers.py
#	new file:   myfeed/databases/README.md
#	new file:   myfeed/databases/fb87181b96a99be45f5a23f4277867ce_auth_user.table
#	new file:   myfeed/databases/fb87181b96a99be45f5a23f4277867ce_auth_user_tag_groups.table
#	new file:   myfeed/databases/fb87181b96a99be45f5a23f4277867ce_feed_item.table
#	new file:   myfeed/databases/fb87181b96a99be45f5a23f4277867ce_friend_request.table
#	new file:   myfeed/databases/fb87181b96a99be45f5a23f4277867ce_item_like.table
#	new file:   myfeed/databases/sql.log
#	new file:   myfeed/databases/storage.db
#	new file:   myfeed/git.zip
#	new file:   myfeed/make_up_data.py
#	new file:   myfeed/models.py
#	new file:   myfeed/settings.py
#	new file:   myfeed/static/README.md
#	new file:   myfeed/static/components/auth.html
#	new file:   myfeed/static/components/auth.js
#	new file:   myfeed/static/css/bulma.css
#	new file:   myfeed/static/favicon.ico
#	new file:   myfeed/static/js/axios.min.js
#	new file:   myfeed/static/js/utils.js
#	new file:   myfeed/static/js/vue.min.js
#	new file:   myfeed/templates/README.md
#	new file:   myfeed/templates/auth.html
#	new file:   myfeed/templates/friends.html
#	new file:   myfeed/templates/generic.html
#	new file:   myfeed/templates/home.html
#	new file:   myfeed/templates/index.html
#	new file:   myfeed/templates/layout.html
#	new file:   myfeed/translations/it.json
#	new file:   todo/__init__.py
#	new file:   todo/__pycache__/__init__.cpython-37.pyc
#	new file:   todo/databases/README
#	new file:   todo/databases/fb87181b96a99be45f5a23f4277867ce_todo.table
#	new file:   todo/databases/sql.log
#	new file:   todo/databases/storage.db
#	new file:   todo/static/css/bulma.css
#	new file:   todo/static/favicon.ico
#	new file:   todo/static/js/axios.min.js
#	new file:   todo/static/js/sugar.min.js
#	new file:   todo/static/js/todo.js
#	new file:   todo/static/js/utils.js
#	new file:   todo/static/js/vue.min.js
#	new file:   todo/templates/index.html
#	new file:   todo/templates/layout.html
#
# Changes not staged for commit:
#	modified:   HW4/databases/fb87181b96a99be45f5a23f4277867ce_contact.table
#	modified:   HW4/databases/fb87181b96a99be45f5a23f4277867ce_phone.table
#	modified:   HW4/databases/sql.log
#	modified:   _default/templates/index.html
#	modified:   _documentation/static/en/.buildinfo
#	modified:   _documentation/static/en/.doctrees/chapter-01.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-02.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-03.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-05.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-06.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-07.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-10.doctree
#	modified:   _documentation/static/en/.doctrees/chapter-12.doctree
#	modified:   _documentation/static/en/.doctrees/environment.pickle
#	modified:   _documentation/static/en/_sources/chapter-02.rst.txt
#	modified:   _documentation/static/en/_sources/chapter-03.rst.txt
#	modified:   _documentation/static/en/_sources/chapter-05.rst.txt
#	modified:   _documentation/static/en/_sources/chapter-06.rst.txt
#	modified:   _documentation/static/en/_sources/chapter-07.rst.txt
#	modified:   _documentation/static/en/_sources/chapter-10.rst.txt
#	modified:   _documentation/static/en/_sources/chapter-12.rst.txt
#	modified:   _documentation/static/en/_static/documentation_options.js
#	modified:   _documentation/static/en/chapter-01.html
#	modified:   _documentation/static/en/chapter-02.html
#	modified:   _documentation/static/en/chapter-03.html
#	modified:   _documentation/static/en/chapter-04.html
#	modified:   _documentation/static/en/chapter-05.html
#	modified:   _documentation/static/en/chapter-06.html
#	modified:   _documentation/static/en/chapter-07.html
#	modified:   _documentation/static/en/chapter-08.html
#	modified:   _documentation/static/en/chapter-09.html
#	modified:   _documentation/static/en/chapter-10.html
#	modified:   _documentation/static/en/chapter-11.html
#	modified:   _documentation/static/en/chapter-12.html
#	modified:   _documentation/static/en/chapter-13.html
#	modified:   _documentation/static/en/chapter-14.html
#	modified:   _documentation/static/en/chapter-15.html
#	modified:   _documentation/static/en/genindex.html
#	modified:   _documentation/static/en/index.html
#	modified:   _documentation/static/en/objects.inv
#	modified:   _documentation/static/en/search.html
#	modified:   _documentation/static/en/searchindex.js
#	modified:   examples/__pycache__/controllers.cpython-37.pyc
#	modified:   hso_project/__pycache__/controllers.cpython-37.pyc
#	modified:   hso_project/controllers.py
#	modified:   hso_project/databases/sql.log
#	modified:   hso_project/databases/storage.db
#	modified:   hso_project/templates/auth.html
#	modified:   hso_project/templates/layout.html
#
# Untracked files:
#	.service/
#	HW4/__pycache__/
#	_default/static/images/
#	examples/socketio/__pycache__/
#	examples/ws/__pycache__/
#	hso_project/static/images/
#	hso_project/templates/global_footer.html
Index Commit#
